app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::auth();
Route::post('/logout', '\App\Http\Controllers\Auth\AuthController@logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'Room', 'middleware' => 'auth', 'prefix' => 'room'], function() {
    Route::get('/index', 'BookingController@index')->name('room.index');
    Route::get('/date/{date}', 'BookingController@show')
        ->middleware(['auth','is_admin'])
        ->name('show_booking_for_date');
    Route::get('/mybooking', 'BookingController@mybooking')->name('room.mybooking');
    Route::get('/mybooking/view/{id}', 'BookingController@view')->name('room.view');
    Route::get('/mybooking/edit/{id}', 'BookingController@edit')->name('room.edit');

    /**
     * API Routes
     * */
    Route::group(['prefix' => 'api'], function() {
        Route::post('/get_available_room', 'BookingController@api_get_available_room')->name('room.api.get_available_room');
        Route::post('/save_room_booking', 'BookingController@api_store_room_booking')->name('room.api.save_room_booking');
        Route::get('/show_all_room_booking', 'BookingController@api_show_all_room_booking')->name('room.api.show_all_room_booking');
        Route::post('/delete_room_booking', 'BookingController@api_delete_room_booking')->name('room.api.delete_room_booking');
        Route::post('/cancel_room_booking', 'BookingController@api_cancel_room_booking')->name('room.api.cancel_room_booking');
        Route::post('/edit_room_booking', 'BookingController@api_edit_room_booking')->name('room.api.edit_room_booking');
        Route::post('/get_my_booking', 'BookingController@api_get_my_booking')->name('room.api.get_my_booking');
        Route::post('/verify_booking', 'BookingController@api_verify_booking')->name('room.api.verify_booking');
    });

    /**
     * Admin Routes
     */
    Route::group(['prefix' => 'admin', 'middleware'=>'is_admin'], function() {
        Route::get('/all','AdminController@all')->name('room.admin.all');
        Route::get('/view/{id}', 'AdminController@view')->name('room.admin.view');

        /**
         * API Routes
         * */
        Route::group(['prefix' => 'api'], function() {
            Route::post('/get_all_booking', 'AdminController@api_get_all_booking')->name('room.admin.api.get_all_booking');
            Route::post('/verify_booking', 'AdminController@api_verify_booking')->name('room.admin.api.verify_booking');
            Route::post('/verify_pending_quotation', 'AdminController@api_verify_pending_quotation')->name('room.admin.api.verify_pending_quotation');
            Route::post('/add_caterer_quotation', 'AdminController@api_add_caterer_quotation')->name('room.admin.api.add_caterer_quotation');
            Route::post('/get_caterer_quotation', 'AdminController@api_get_caterer_quotation')->name('room.admin.api.get_caterer_quotation');
            Route::post('/delete_caterer_quotation', 'AdminController@api_delete_caterer_quotation')->name('room.admin.api.delete_caterer_quotation');
            Route::post('/select_caterer_quotation', 'AdminController@api_select_caterer_quotation')->name('room.admin.api.select_caterer_quotation');
            Route::post('/get_rooms_parameter', 'AdminController@api_get_rooms_parameter')->name('room.admin.api.get_rooms_parameter');
            Route::post('/save_room_parameter', 'AdminController@api_save_room_parameter')->name('room.admin.api.save_room_parameter');
            Route::post('/delete_room_parameter', 'AdminController@api_delete_room_parameter')->name('room.admin.api.delete_room_parameter');
            Route::post('/get_room_setup_parameter', 'AdminController@api_get_room_setup_parameter')->name('room.admin.api.get_room_setup_parameter');
            Route::post('/save_room_setup_parameter', 'AdminController@api_save_room_setup_parameter')->name('room.admin.api.save_room_setup_parameter');
            Route::post('/delete_room_setup_parameter', 'AdminController@api_delete_room_setup_parameter')->name('room.admin.api.delete_room_setup_parameter');
            Route::post('/get_divisions_parameter', 'AdminController@api_get_divisions_parameter')->name('room.admin.api.get_divisions_parameter');
            Route::post('/save_divisions_parameter', 'AdminController@api_save_divisions_parameter')->name('room.admin.api.save_divisions_parameter');
            Route::post('/delete_divisions_parameter', 'AdminController@api_delete_divisions_parameter')->name('room.admin.api.delete_divisions_parameter');
            Route::post('/get_food_setup_parameter', 'AdminController@api_get_food_setup_parameter')->name('room.admin.api.get_food_setup_parameter');
            Route::post('/save_food_setup_parameter', 'AdminController@api_save_food_setup_parameter')->name('room.admin.api.save_food_setup_parameter');
            Route::post('/delete_food_setup_parameter', 'AdminController@api_delete_food_setup_parameter')->name('room.admin.api.delete_food_setup_parameter');
            Route::post('/get_foods_parameter', 'AdminController@api_get_foods_parameter')->name('room.admin.api.get_foods_parameter');
            Route::post('/save_foods_parameter', 'AdminController@api_save_foods_parameter')->name('room.admin.api.save_foods_parameter');
            Route::post('/delete_foods_parameter', 'AdminController@api_delete_foods_parameter')->name('room.admin.api.delete_foods_parameter');
            Route::post('/get_drinks_parameter', 'AdminController@api_get_drinks_parameter')->name('room.admin.api.get_drinks_parameter');
            Route::post('/save_drinks_parameter', 'AdminController@api_save_drinks_parameter')->name('room.admin.api.save_drinks_parameter');
            Route::post('/delete_drinks_parameter', 'AdminController@api_delete_drinks_parameter')->name('room.admin.api.delete_drinks_parameter');
        });
    });
});

Route::group(['namespace' => 'Vehicle', 'middleware' => 'auth', 'prefix' => 'vehicle'], function() {
    Route::get('/index', 'BookingController@index')->name('vehicle.index');
    Route::get('/date/{date}', 'BookingController@show')
        ->middleware(['auth','is_admin'])
        ->name('show_booking_for_date');
    Route::get('/mybooking', 'BookingController@mybooking')->name('vehicle.mybooking');
    Route::get('/mybooking/view/{id}', 'BookingController@view')->name('vehicle.view');
    Route::get('/mybooking/edit/{id}', 'BookingController@edit')->name('vehicle.edit');
    Route::get('/jobs', 'BookingController@show_jobs')->name('vehicle.jobs');
    Route::get('/jobs/view/{id}', 'BookingController@view_jobs')->name('vehicle.jobs.view');
    Route::get('/report', 'BookingController@report')->name('vehicle.report');

    /**
     * API Routes
     * */
    Route::group(['prefix' => 'api'], function() {
        Route::get('/show_all_vehicle_booking', 'BookingController@api_show_all_vehicle_booking')->name('vehicle.api.show_all_vehicle_booking');
        Route::post('/get_available_vehicle', 'BookingController@api_get_available_vehicle')->name('vehicle.api.get_available_vehicle');
        Route::post('/save_vehicle_booking', 'BookingController@api_store_vehicle_booking')->name('vehicle.api.save_vehicle_booking');
        Route::post('/edit_vehicle_booking', 'BookingController@api_edit_vehicle_booking')->name('vehicle.api.edit_vehicle_booking');
        Route::post('/delete_vehicle_booking', 'BookingController@api_delete_vehicle_booking')->name('vehicle.api.delete_vehicle_booking');
        Route::post('/cancel_vehicle_booking', 'BookingController@api_cancel_vehicle_booking')->name('vehicle.api.cancel_vehicle_booking');
        Route::post('/get_my_booking', 'BookingController@api_get_my_booking')->name('vehicle.api.get_my_booking');
        Route::post('/get_my_jobs', 'BookingController@api_get_my_jobs')->name('vehicle.api.get_my_jobs');
        Route::post('/save_vehicle_logbook', 'BookingController@api_save_vehicle_logbook')->name('vehicle.api.save_vehicle_logbook');
        Route::post('/upload_vehicle_log_files', 'BookingController@api_upload_vehicle_log_files')->name('vehicle.api.upload_vehicle_log_files');
        Route::post('/get_vehicle_log_files', 'BookingController@api_get_vehicle_log_files')->name('vehicle.api.get_vehicle_log_files');
        Route::post('/delete_vehicle_log_file', 'BookingController@api_delete_vehicle_log_file')->name('vehicle.api.delete_vehicle_log_file');
        Route::post('/generate_report', 'BookingController@api_generate_report')->name('vehicle.api.generate_report');
        Route::post('/job_done', 'BookingController@api_job_done')->name('vehicle.api.job_done');
    });

    /**
     * Admin Routes
     */
    Route::group(['prefix' => 'admin', 'middleware'=>'is_admin'], function() {
        Route::get('/all', 'AdminController@all')->name('vehicle.admin.all');
        Route::get('/view/{id}', 'AdminController@view')->name('vehicle.admin.view');
        Route::get('/edit/{id}', 'AdminController@edit')->name('vehicle.admin.edit');
        Route::get('/report', 'AdminController@report')->name('vehicle.admin.report');

        /**
         * API Routes
         * */
        Route::group(['prefix' => 'api'], function() {
            Route::post('/get_all_booking', 'AdminController@api_get_all_booking')->name('vehicle.admin.api.get_all_booking');
            Route::post('/verify_booking', 'AdminController@api_verify_booking')->name('vehicle.admin.api.verify_booking');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * App\User
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property int $is_admin
 * @property string|null $remember_token
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereIsAdmin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereUpdatedAt($value)
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\MeetingBooking[] $meetingBooking
 * @mixin \Eloquent
 */

class User extends Authenticatable
{
    const ADMIN = 1;
    const NORMAL_USER = 0;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'division_id', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function meetingBooking() {
        return $this->hasMany(MeetingBooking::class);
    }

    public function isAdmin() {
        return $this->is_admin == self::ADMIN;
    }

    public function division() {
        return $this->belongsTo(Division::class);
    }

    public function carBooking() {
        return $this->hasMany(CarBooking::class);
    }

    public function getIsDriverAttribute() {
        return $this->driver != null;
    }

    public function driver() {
        return $this->hasOne(Driver::class);
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('constant.APP_NAME') }}</title>

        <!-- Custom fonts for this template-->
        <link href="{{ asset('template/vendor/fontawesome-free/css/all.css') }}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{{ asset('template/css/sb-admin-2.css') }}" rel="stylesheet">

        <!-- FullCalendar CSS-->
        <link href="{{ asset('assets/fullcalendar-4/packages/core/main.css') }}" rel='stylesheet' />
        <link href="{{ asset('assets/fullcalendar-4/packages/daygrid/main.css') }}" rel='stylesheet' />
        <link href="{{ asset('assets/fullcalendar-4/packages/timegrid/main.css') }}" rel='stylesheet' />

        <!-- DataTables CSS-->
        <link href="{{ asset('template/vendor/datatables/dataTables.bootstrap4.css') }}" rel='stylesheet' />

        <!-- SweetAlert2 CSS -->
        <link href="{{ asset('assets/sweetalert2/dist/sweetalert2.css') }}" rel='stylesheet' />
        @yield('styles')

    <!-- Bootstrap core JavaScript-->
        <script src="{{ asset('template/vendor/jquery/jquery.min.js') }}"></script>
        <script src="{{ asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{{ asset('template/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

        <!-- jQuery Validation Plugin-->
        <script src="{{ asset('assets/jquery-validation/dist/jquery.validate.js') }}"></script>
        <script src="{{ asset('assets/jquery-validation/dist/additional-methods.js') }}"></script>

        <!-- FullCalendar JavaScript-->
        <script src="{{ asset('assets/fullcalendar-4/packages/core/main.js') }}"></script>
        <script src="{{ asset('assets/fullcalendar-4/packages/daygrid/main.js') }}"></script>
        <script src="{{ asset('assets/fullcalendar-4/packages/interaction/main.js') }}"></script>
        <script src="{{ asset('assets/fullcalendar-4/packages/timegrid/main.js') }}"></script>
        <script src="{{ asset('assets/fullcalendar-4/packages/moment/main.js') }}"></script>

        <!-- DataTables Javascript-->
        <script src="{{ asset('template/vendor/datatables/jquery.dataTables.js') }}"></script>
        <script src="{{ asset('template/vendor/datatables/dataTables.bootstrap4.js') }}"></script>

        <!-- Moment.js -->
        <script src="{{ asset('assets/moment/moment.min.js') }}"></script>

        <!-- Tempusdominus Datepicker-->
        <script type="text/javascript" src="{{ asset('assets/tempusdominus-bootstrap-4/build/js/tempusdominus-bootstrap-4.js')}}"></script>
        <link rel="stylesheet" href="{{ asset('assets/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.css')}}" />

        <!-- SweetAlert2 JS -->
        <script type="text/javascript" src="{{ asset('assets/sweetalert2/dist/sweetalert2.all.js')}}"></script>

        <!-- jQuery BlockUI JS -->
        <script type="text/javascript" src="{{ asset('assets/jquery.blockUI/jquery.blockUI.js')}}"></script>
    </head>
    <body id="page-top">
        <!-- Page Wrapper -->
        <div id="wrapper">

            @include('layouts.sidemenu')

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    @include('layouts.topbar')

                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        <div class="row">
                            @yield('content')
                        </div>
                    </div>
                    <!-- /.container-fluid -->

                </div>
                <!-- End of Main Content -->

                @include('layouts.footer')

            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        @include('layouts.logoutmodal')



        <!-- Custom scripts for all pages-->
        <script src="{{ asset('template/js/sb-admin-2.min.js') }}"></script>
        @yield('scripts')

    </body>
</html>

resources/views/layouts/app_alt.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('constant.APP_NAME') }}</title>

    <!-- Fonts -->
    <link href="{{ asset('template/vendor/fontawesome-free/css/all.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('template/css/sb-admin-2.css') }}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">

                        @yield('content')

                        <hr>
                        @if (Auth::guest())
                            <div class="text-center">
                                <a class="small" href="{{ url('/login') }}">Login</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="{{ url('/register') }}">Register</a>
                            </div>
                        @endif
                        </div></div>
                    </div>

                </div>
            </div>

        </div>

    </div>

</div>



<!-- Bootstrap core JavaScript-->
<script src="{{ asset('template/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('template/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('template/js/sb-admin-2.min.js') }}"></script>
@yield('scripts')

</body>

</html>

resources/views/layouts/footer.blade.php
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="row copyright" style="justify-content: space-between;">
                <div class="col-xs-6">Copyright &copy; SEDA {{ date('Y') }}</div>
                <div class="col-xs-6">Developed with &#128149; by Digital Services Division</div>
            </div>
        </div>
    </footer>
    <!-- End of Footer -->

resources/views/layouts/logoutmodal.blade.php
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{{ url('/logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        Logout
                    </a>

                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </div>
            </div>
        </div>
    </div>

resources/views/layouts/sidemenu.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{url('/home')}}">
        <div class="sidebar-brand-icon">
            <i class="fas fa-calendar-check"></i>
        </div>
        <div class="sidebar-brand-text mx-0">{{ config('constant.APP_NAME') }}<sup>1.0<sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {{ (\Request::route()->getName() == 'home') ? 'active' : null }}">
        <a class="nav-link" href="{{url('/home')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Booking Type
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item {{ (\Request::is('room/*')) ? 'active' : null }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-chalkboard-teacher"></i>
            <span>Meeting Room</span>
        </a>
        <div id="collapseTwo" class="collapse {{ (\Request::is('room/*')) ? 'show' : null }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Action Menu:</h6>
                <a class="collapse-item {{ (\Request::route()->getName() == 'room.index') ? 'active' : null }}" href="{{route('room.index')}}">Apply</a>
                <a class="collapse-item {{ (Request::is('room/mybooking*')) ? 'active' : null }}" href="{{route('room.mybooking')}}">My Booking</a>
                @if(\Auth::user()->is_admin)
                <h6 class="collapse-header">Admin Menu:</h6>
                <a class="collapse-item {{ (in_array(Request::route()->getName(),['room.admin.all', 'room.admin.view'])) ? 'active' : null }}" href="{{route('room.admin.all')}}">All Booking</a>
                @endif
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item {{ (\Request::is('vehicle/*')) ? 'active' : null }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-car"></i>
            <span>Vehicle</span>
        </a>
        <div id="collapseUtilities" class="collapse {{ (\Request::is('vehicle/*')) ? 'show' : null }}" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Action Menu:</h6>
                <a class="collapse-item {{ (\Request::route()->getName() == 'vehicle.index') ? 'active' : null }}" href="{{route('vehicle.index')}}">Apply</a>
                <a class="collapse-item {{ (Request::is('vehicle/mybooking*')) ? 'active' : null }}" href="{{route('vehicle.mybooking')}}">My Booking</a>
                @if(\Auth::user()->is_driver)
                <h6 class="collapse-header">Driver Menu:</h6>
                <a class="collapse-item {{ (Request::is('vehicle/jobs*'))  ? 'active' : null }}" href="{{route('vehicle.jobs')}}">Jobs</a>
                <a class="collapse-item {{ (Request::is('vehicle/report*'))  ? 'active' : null }}" href="{{route('vehicle.report')}}">Reporting</a>
                @endif
                @if(\Auth::user()->is_admin)
                <h6 class="collapse-header">Admin Menu:</h6>
                <a class="collapse-item {{ (in_array(Request::route()->getName(),['vehicle.admin.all', 'vehicle.admin.view'])) ? 'active' : null }}" href="{{route('vehicle.admin.all')}}">All Booking</a>
                <a class="collapse-item {{ (Request::is('vehicle/admin/report*')) ? 'active' : null }}" href="{{route('vehicle.admin.report')}}">Reporting</a>
                @endif
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    @if(\Auth::user()->is_admin)
    <!-- Heading -->
    <div class="sidebar-heading">
        Administrator
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item {{ (\Request::is('admin/*')) ? 'active' : null }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdmin" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cogs"></i>
            <span>System Setting</span>
        </a>
        <div id="collapseAdmin" class="collapse {{ (\Request::is('admin/*')) ? 'show' : null }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Global Setting:</h6>
                <a class="collapse-item {{ (Request::is('admin/setting/global/parameter_management*')) ? 'active' : null }}" href="{{route('admin.setting.global.parameter')}}">Parameter Management</a>
                <a class="collapse-item {{ (Request::is('admin/setting/global/user_management*')) ? 'active' : null }}" href="{{route('admin.setting.global.user_management')}}">User Management</a>

                <h6 class="collapse-header">Meeting Room Setting:</h6>
                <a class="collapse-item {{ (Request::is('admin/setting/room*')) ? 'active' : null }}" href="{{route('admin.setting.room.parameter')}}">Parameter Management</a>

                <h6 class="collapse-header">Vehicle Setting:</h6>
                <a class="collapse-item {{ (Request::is('admin/setting/vehicle/parameter_management*')) ? 'active' : null }}" href="{{route('admin.setting.vehicle.parameter')}}">Parameter Management</a>
                <a class="collapse-item {{ (Request::is('admin/setting/vehicle/driver_management*')) ? 'active' : null }}" href="{{route('admin.setting.vehicle.driver_management')}}">Driver Management</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    @endif

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->